---
abstract: 'The great new Maple!'
author:
  - 'Eugene Au <eugene.au@live.ca>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Maple
provides:
  Maple:
    file: lib/Maple.pm
    version: 0.01
  Maple::Class:
    file: lib/Maple/Class.pm
    version: 0.01
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
